"""Constants for SecurePDF V1 schema.

Warning and Error codes matching the Go engine as defined in engine-contract.md.
"""

# Warning codes
WARN_WEAK_CRYPTO_REQUESTED = "W001"
WARN_WEAK_CRYPTO_REJECTED = "W002"
WARN_VIEWER_DEPENDENT_ACK = "W003"
WARN_UNSUPPORTED_PDF_FEATURE = "W004"
WARN_LABEL_PARTIALLY_APPLIED = "W005"
WARN_PROVENANCE_PARTIALLY_APPLIED = "W006"
WARN_TAMPER_HASH_EMBED_FAILED = "W007"
WARN_UNKNOWN_POLICY_FIELD = "W008"

# Error codes
ERR_POLICY_INVALID = "E001"
ERR_INPUT_PDF_INVALID = "E002"
ERR_INPUT_PDF_UNSUPPORTED = "E003"
ERR_ENCRYPTION_FAILED = "E004"
ERR_LABEL_FAILED = "E005"
ERR_PROVENANCE_FAILED = "E006"
ERR_TAMPER_HASH_FAILED = "E007"
ERR_OUTPUT_WRITE_FAILED = "E008"
ERR_RUNTIME_TIMEOUT = "E009"
ERR_RUNTIME_MEMORY_LIMIT = "E010"
ERR_INPUT_READ_FAILED = "E011"
ERR_INTERNAL_ERROR = "E099"
